### ISSUE TITLE
Code reivew about pull request #2

### ISSUE THREAD

**Issue by jongfeel** [eunyeong-so/Learn-Anything#3]
### Code review

- #2 에 구현한 내용은 짧지만 흥미로운 것 같습니다.
- event invoker를 사용했다는 점
- inheritance + override method를 써서 객체지향적으로 만들어 보려는 흔적

짧게 해볼 수 있는 미니 프로젝트로는 아주 좋은 것 같은데
몇 가지 문제점이 있습니다.

### Problems

- click event의 효율성 => collider를 찾을 수 있다면 바로 GetComponent< Monster >().Damage()를 호출하는게 더 효율적임.
  - event 호출과 method 호출의 차이점의 인식 필요
- Monster class 상속의 이유 => 비효율적인 메서드 3회 호출
  - 상속이 들어가면 다형성을 충분히 활용할 필요가 있음

### So, I propose to you training programming skill. 

1. 게임의 전체적인 시작과, 끝, 게임 플레이 방법, 레벨 디자인 등에 대한 내용을 기술 (요구사항 + 매뉴얼 느낌)
2. 1의 내용을 바탕으로 class 설계 (class diagram 보다는 collaboration diagram으로)
3. 설계한 내용을 바탕으로 테스트 코드 작성 (TDD)
4. 테스트를 만족시키는 실제 로직 작성

으로 해 보면 좋겠습니다.

만약 해볼 의향이 있다면 같이 해보면 좋을 것 같고요
1,2,3,4 milestone 단계를 밟아 차례대로 해보면 재밌을 것 같습니다.

**Comment by eunyeong-so** [comment]
제가 초대를 아무도 안드렸던 것 같아서..! 초대장을 늦게나마 보냈습니다. 
저도 상속 부분에 있어서 효율적인지 의심이 갔었는데 콕 집어주셨네요. 
방향 제시 해주신 부분 참고하여 고민을 해보겠습니다! 다음 모각코가 기대되네요!!
